// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvw_05qNyy7AD4oYBlIaPxHaaWzQh2Ja4',
    appId: '1:881118593980:web:ff96b78c69f5c15ceda1b9',
    messagingSenderId: '881118593980',
    projectId: 'my-drawing-firebase',
    authDomain: 'my-drawing-firebase.firebaseapp.com',
    storageBucket: 'my-drawing-firebase.firebasestorage.app',
    measurementId: 'G-BDRH25R8RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWSvWvvPwllbF8qaH61YGz33CC1cx-iKE',
    appId: '1:881118593980:android:5d3aa1c69eb9d6adeda1b9',
    messagingSenderId: '881118593980',
    projectId: 'my-drawing-firebase',
    storageBucket: 'my-drawing-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACT0Zjn5bWLbeuz-88qRwPWiHTQjvcio8',
    appId: '1:881118593980:ios:7a5e209eecf05caceda1b9',
    messagingSenderId: '881118593980',
    projectId: 'my-drawing-firebase',
    storageBucket: 'my-drawing-firebase.firebasestorage.app',
    iosBundleId: 'com.example.myDrawingFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACT0Zjn5bWLbeuz-88qRwPWiHTQjvcio8',
    appId: '1:881118593980:ios:7a5e209eecf05caceda1b9',
    messagingSenderId: '881118593980',
    projectId: 'my-drawing-firebase',
    storageBucket: 'my-drawing-firebase.firebasestorage.app',
    iosBundleId: 'com.example.myDrawingFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvw_05qNyy7AD4oYBlIaPxHaaWzQh2Ja4',
    appId: '1:881118593980:web:90114207b5ccc4f4eda1b9',
    messagingSenderId: '881118593980',
    projectId: 'my-drawing-firebase',
    authDomain: 'my-drawing-firebase.firebaseapp.com',
    storageBucket: 'my-drawing-firebase.firebasestorage.app',
    measurementId: 'G-P3ZKCCT59X',
  );
}
