import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';

import 'controllers/auth_controller.dart';
import 'controllers/drawing_controller.dart';
import 'services/firebase_service.dart';
import 'services/cloudinary_service.dart';
import 'services/ai_service.dart';
import 'firebase_options.dart'; // generated by FlutterFire

// Screens
import 'screens/auth/login_screen.dart';
import 'screens/auth/signup_screen.dart';
import 'screens/home/gallery_screen.dart';
import 'screens/home/home_screen.dart';
import 'screens/draw/canvas_screen.dart';
import 'screens/onboarding/onboarding_screen.dart';
import 'screens/splash/splash_screen.dart';
import 'screens/profile/user_profile_screen.dart';

// Theme
import 'core/theme.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  final firebaseService = FirebaseService();
  final cloudinaryService = CloudinaryService();
  final aiService = AIService();

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(
            create: (_) => AuthController(firebaseService)),
        ChangeNotifierProvider(
            create: (_) => DrawingController(
              firebaseService,
              cloudinaryService,
              aiService,
            )),
      ],
      child: const DrawifyApp(),
    ),
  );
}

class DrawifyApp extends StatelessWidget {
  const DrawifyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Drawify',
      theme: AppTheme.lightTheme,
      initialRoute: '/splash',
      routes: {
        '/splash': (_) => const SplashScreen(),
        '/onboarding': (_) => const OnboardingScreen(),
        '/canvas': (_) => const CanvasScreen(),
        '/home': (_) => const HomeScreen(),
        '/login': (_) => const LoginScreen(),
        '/signup': (_) => const SignupScreen(),
        '/gallery': (_) => const GalleryScreen(),
        '/profile': (_) => const UserProfileScreen(),
      },
    );
  }
}
